"""
code_01_matrices.py  ->  Table 3, Appendix A matrices
=====================================================
Covers: the embeddings of Theorems 1 and 2, their sparsity,
and the precise transition statements of each theorem.

Produces
  Tables/tab_dimensions.tex        Table 3: embedded dimension and sparsity
  Tables/app_matrices_E*.tex       Appendix A: symbolic A_t and B_t, k=3, r=2
  Tables/app_matrices_E1_k2r1.tex  the 3x3 case used in Theorem 3
  Output/structural_checks.csv     row-stochasticity over a (k, r) grid
"""

from __future__ import annotations

import numpy as np
import sympy as sp

import mcem_core as C
from common import (banner, latex_bmatrix, latex_table, save_environment,
                    write_csv, write_table)

P = sp.symbols("p_0 p_1 p_2", nonnegative=True)
SUB = {"E1": "1", "E2": "2", "E3": "3", "E4": "4"}


def dump_matrices(family, k, r, fname):
    A, B = C.build_matrices(family, k, r, P, dtype=object)
    states, _ = C.state_space(family, k, r)
    order = ",\\; ".join(C.state_label(s) for s in states)
    txt = [
        "%% generated by code_01_matrices.py",
        "%% %s, k=%d, r=%d, s=%d" % (family, k, r, A.shape[0]),
        "\\[ \\Omega = \\left\\{ %s \\right\\} \\]" % order,
        "\\[",
        "\\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}"
        "{!}{$\\displaystyle",
        "\\boldsymbol{A}_t = " + latex_bmatrix(A) + ", \\quad",
        "\\boldsymbol{B}_t = " + latex_bmatrix(B),
        "$}",
        "\\]",
        "",
    ]
    write_table(fname, "\n".join(txt))
    return A, B


def main():
    save_environment()

    banner("1.1  Symbolic transition matrices")
    dump_matrices("E1", 2, 1, "app_matrices_E1_k2r1.tex")
    for fam in C.FAMILIES:
        dump_matrices(fam, 3, 2, "app_matrices_%s_k3r2.tex" % fam)

    banner("1.2  Structural checks over a (k, r) grid")
    rows, allok = [], True
    for fam in C.FAMILIES:
        for k in (2, 3, 4, 5, 6):
            for r in (0, 1, 2, 3):
                A, B = C.build_matrices(fam, k, r, P, dtype=object)
                s = A.shape[0]
                rs = sp.simplify((sp.Matrix((A + B).tolist()) * sp.ones(s, 1))
                                 .subs(P[0], 1 - P[1] - P[2]))
                stoch = all(sp.simplify(rs[i] - 1) == 0 for i in range(s))
                formula = C.state_dimension(fam, k, r)
                nonneg = all("-" not in str(v)
                             for v in list(A.flatten()) + list(B.flatten()))
                allok &= bool(stoch and nonneg and s == formula)
                rows.append([fam, k, r, s, formula, s == formula, stoch, nonneg,
                             C.sparsity(fam, k, r)])
    write_csv("structural_checks.csv",
              ["family", "k", "r", "s_built", "s_formula", "match",
               "row_stochastic", "nonnegative", "nnz_A_plus_B"], rows)
    print("  every check passed: %s" % allok)

    banner("1.3  Table 3: embedded dimension and sparsity")
    grid = [(2, 1), (3, 1), (3, 2), (4, 2), (5, 2), (5, 3)]
    tex_rows, csv_rows = [], []
    print("  %-6s %-6s | %-18s | %-18s" % ("k", "r", "strict (E1, E3)",
                                           "threshold (E2, E4)"))
    print("  %-6s %-6s | %8s %9s | %8s %9s"
          % ("", "", "s", "nnz", "s", "nnz"))
    for k, r in grid:
        s1 = C.state_dimension("E1", k, r)
        s2 = C.state_dimension("E2", k, r)
        n1 = C.sparsity("E1", k, r)
        n2 = C.sparsity("E2", k, r)
        print("  %-6d %-6d | %8d %9d | %8d %9d" % (k, r, s1, n1, s2, n2))
        tex_rows.append([k, r, s1, n1, s2, n2])
        csv_rows.append([k, r, s1, n1, s2, n2])
    write_csv("dimensions.csv",
              ["k", "r", "s_strict", "nnz_strict", "s_threshold",
               "nnz_threshold"], csv_rows)

    write_table("tab_dimensions.tex", latex_table(
        caption=("Embedded dimension $s$ and the number of non-zero entries of "
                 "$\\boldsymbol{A}_t+\\boldsymbol{B}_t$. The strict families "
                 "$\\mathcal{E}_1,\\mathcal{E}_3$ share the state space of "
                 "Theorem~\\ref{thm:strict}; the gap-threshold families "
                 "$\\mathcal{E}_2,\\mathcal{E}_4$ additionally carry the age "
                 "index $a$."),
        label="tab:dimensions",
        colspec="cc cc cc",
        header=[["\\multicolumn{2}{c}{Parameters} & "
                 "\\multicolumn{2}{c}{Strict ($\\mathcal{E}_1,\\mathcal{E}_3$)} & "
                 "\\multicolumn{2}{c}{Threshold ($\\mathcal{E}_2,\\mathcal{E}_4$)}"],
                ["$k$", "$r$",
                 "$s_1=1+(k-1)(r+1)$", "nnz",
                 "$s_2=1+\\tfrac{(r+1)k(k-1)}{2}$", "nnz"]],
        rows=[[str(c) for c in row] for row in tex_rows],
        notes=("Both matrices carry at most three non-zero entries per row, so "
               "$\\mathrm{nnz}(\\boldsymbol{A}_t)+\\mathrm{nnz}"
               "(\\boldsymbol{B}_t)=O(s)$; a sparse implementation of the "
               "embedding therefore costs $O(s)$ per trial, not $O(s^2)$.")))


if __name__ == "__main__":
    main()
