"""
code_02_recursions.py  ->  Table 3 and Appendix B
=================================================
The determinant det[I - w(A + zB)] is a polynomial in w of degree at most s,
and by Cramer's rule its coefficients are the coefficients of a linear
recursion for the conditional generating function phi_n(z).  This script
extracts that recursion for a range of settings, writes the symbolic form for
the appendix, and checks the recursion against the matrix evaluation.

The check matters.  The recursion is obtained by symbolic algebra and the
matrix evaluation by arithmetic on non-negative numbers; they share the state
space and nothing else, so agreement is evidence that the algebra is right.

Outputs: Tables/tab_recursions.tex, Tables/app_recursions.tex,
         Output/recursions.csv
"""

from __future__ import annotations

import numpy as np
import sympy as sp

import embedding as E
from common import (banner, latex_table, sci_latex, save_environment,
                    write_csv, write_table)

P = (0.35, 0.35, 0.30)
GRID = (("E1", 2, 1), ("E2", 2, 1), ("E3", 2, 1), ("E4", 2, 1),
        ("E1", 3, 1), ("E2", 3, 1), ("E3", 3, 1), ("E4", 3, 1),
        ("E1", 3, 2), ("E2", 3, 2), ("E3", 3, 2), ("E4", 3, 2),
        ("E1", 4, 2), ("E4", 4, 2))
SYMBOLIC = (("E1", 2, 1), ("E2", 2, 1), ("E3", 2, 1), ("E4", 2, 1))


def check(family, k, r, p, nmax):
    """Recursion against the matrix evaluation of the mass function."""
    rec = E.scalar_recursion(family, k, r, p)
    a = E.pmf_from_scalar_recursion(nmax, family, k, r, p, rec=rec)
    b = E.pmf(nmax, family, k, r, p)
    m = min(len(a), len(b))
    return rec, float(np.max(np.abs(a[:m] - b[:m])))


def symbolic_form(family, k, r):
    """The recursion with the cell probabilities left as symbols."""
    rec = E.scalar_recursion(family, k, r, symbolic=True)
    z = rec["symbols"][-1]
    lines = []
    for j, c in enumerate(rec["den"], start=1):
        if c == 0:
            continue
        lines.append("%s\\,\\varphi_{n-%d}(z)" % (sp.latex(sp.factor(c)), j))
    return rec["order"], "\n  + ".join(lines)


def main(nmax=80):
    save_environment()

    banner("Table 3: scalar recursions from det[I - w(A + zB)]")
    print("  %-4s %3s %3s %6s %8s %14s"
          % ("fam", "k", "r", "s", "order m", "max |rec-mat|"))
    rows, tex, worst = [], [], 0.0
    for family, k, r in GRID:
        rec, err = check(family, k, r, P, nmax)
        worst = max(worst, err)
        s = E.state_dimension(family, k, r)
        print("  %-4s %3d %3d %6d %8d %14.2e"
              % (family, k, r, s, rec["order"], err))
        rows.append([family, k, r, s, rec["order"], err])
        tex.append(["$\\mathcal{E}_%s$" % family[1], "%d" % k, "%d" % r,
                    "%d" % s, "%d" % rec["order"], sci_latex(err)])
    write_csv("recursions.csv",
              ["family", "k", "r", "s", "order", "max_abs_diff"], rows)

    write_table("tab_recursions.tex", latex_table(
        caption=("Order of the scalar recursion obtained from "
                 "$\\det[\\boldsymbol{I}-w(\\boldsymbol{A}+z\\boldsymbol{B})]$, "
                 "with the embedded dimension for comparison. The last column "
                 "is the largest absolute difference between the mass function "
                 "computed from the recursion and from the matrix form at "
                 "$n=%d$, $p_0=p_1=0.35$, $p_2=0.30$." % nmax),
        label="tab:recursions",
        colspec="l cc cc c",
        header=[["Family", "$k$", "$r$", "$s$", "order $m$",
                 "Max difference"]],
        rows=tex,
        notes=("The order never exceeds $s$, as Proposition~\\ref{prop:scalar} "
               "requires, and is often strictly smaller because factors of the "
               "determinant cancel. Agreement with the matrix form is at the "
               "level of double-precision rounding throughout, the largest "
               "difference anywhere being %s."
               % sci_latex(worst))))

    banner("Appendix B: symbolic recursions")
    out = ["%% generated by code_02_recursions.py; do not edit by hand"]
    for family, k, r in SYMBOLIC:
        order, body = symbolic_form(family, k, r)
        print("  %s k=%d r=%d: order %d" % (family, k, r, order))
        out += [
            "\\paragraph{$\\mathcal{E}_%s$ with $k=%d$, $r=%d$ (order %d).}"
            % (family[1], k, r, order),
            "\\begin{align*}",
            "\\varphi_n(z) &= " + body.replace("\n  + ", " \\\\ &\\quad + "),
            "\\end{align*}", "",
        ]
    write_table("app_recursions.tex", "\n".join(out))
    return rows


if __name__ == "__main__":
    raise SystemExit(0 if main() else 0)
