"""
code_08_recursions.py  ->  Table 4, Appendix B
===============================================
Covers: scalar recursions valid for
arbitrary k, r and all four families, rather than only for k = 2, r = 1.

Since  Phi(z,w) = pi_0 [I - w(A + zB)]^{-1} 1'  is rational in w with
denominator det[I - w(A + zB)] = 1 - sum_j c_j(z) w^j of degree m <= s,

    phi_n(z) = sum_{j=1}^{m} c_j(z) phi_{n-j}(z),

and reading off the coefficient of z^x turns each c_j(z) into a shift in x:

    f_n(x) = sum_j sum_i c_{j,i} f_{n-j}(x - i).

This script derives the coefficients symbolically, checks the k = 2, r = 1
case against Corollary 1 as printed, verifies the generated recursion against
the matrix embedding for a grid of settings, and writes the recursions out as
a LaTeX appendix.

Outputs: Tables/tab_recursions.tex, Tables/app_recursions.tex,
         Output/recursion_orders.csv
"""

from __future__ import annotations

import argparse

import numpy as np
import sympy as sp

import mcem_core as C
from common import banner, latex_table, save_environment, write_csv, write_table

GRID = [("E1", 2, 1), ("E1", 3, 1), ("E2", 2, 1), ("E2", 3, 1),
        ("E3", 2, 1), ("E3", 3, 1), ("E4", 2, 1), ("E4", 3, 1)]
MATH = {"E1": "\\mathcal{E}_1", "E2": "\\mathcal{E}_2",
        "E3": "\\mathcal{E}_3", "E4": "\\mathcal{E}_4"}


def check_corollary_1():
    rec = C.scalar_recursion("E1", 2, 1, symbolic=True)
    p0, p1, p2, z = rec["symbols"]
    printed = [p0 + p1,
               p2 * (p0 + z * p2),
               p1 * p2 * (p0 + p1 + z * p2)]
    ok = []
    for j, (got, want) in enumerate(zip(rec["den"], printed), start=1):
        same = sp.simplify(sp.expand(got - want)) == 0
        ok.append(same)
        print("    c_%d(z) = %s      [Corollary 1: %s]"
              % (j, sp.simplify(got), "match" if same else "MISMATCH"))
    return all(ok) and rec["order"] == 3


def latex_block(family, k, r):
    rec = C.scalar_recursion(family, k, r, symbolic=True)
    terms = []
    for j, e in enumerate(rec["den"], start=1):
        if sp.simplify(e) == 0:
            continue
        terms.append("\\left(%s\\right)\\varphi_{n-%d}(z)"
                     % (sp.latex(sp.factor(e)), j))
    body = " \\nonumber \\\\ &\\quad + ".join(terms)
    return ("\\paragraph{$%s$ with $k=%d$, $r=%d$ ($s=%d$, order $m=%d$).}\n"
            "\\begin{align}\n\\varphi_n(z) &= %s\n\\end{align}\n"
            % (MATH[family], k, r, rec["s"], rec["order"], body)), rec


def main(grid=GRID, nmax=80):
    save_environment()

    banner("A. k = 2, r = 1 against Corollary 1 as printed")
    print("  agreement:", check_corollary_1())

    banner("B. General (family, k, r): derive, verify, and write the appendix")
    blocks = ["% generated by code_08_recursions.py", ""]
    rows = []
    print("  %-4s %-3s %-3s %6s %6s %14s"
          % ("fam", "k", "r", "s", "m", "max |PMF diff|"))
    for family, k, r in grid:
        block, rec_sym = latex_block(family, k, r)
        blocks.append(block)
        rec = C.scalar_recursion(family, k, r, C.symmetric_p(0.35))
        worst = 0.0
        for p2 in (0.2, 0.35, 0.6):
            p = C.symmetric_p(p2)
            rnum = C.scalar_recursion(family, k, r, p)
            for n in (12, 30, nmax):
                a = C.pmf(n, family, k, r, p)
                b = C.pmf_from_scalar_recursion(n, family, k, r, p, rnum)
                L = min(len(a), len(b))
                worst = max(worst, float(np.max(np.abs(a[:L] - b[:L]))))
        print("  %-4s %-3d %-3d %6d %6d %14.3e"
              % (family, k, r, rec_sym["s"], rec_sym["order"], worst))
        rows.append([family, k, r, rec_sym["s"], rec_sym["order"], worst])

    write_table("app_recursions.tex", "\n".join(blocks))
    write_csv("recursion_orders.csv",
              ["family", "k", "r", "s", "order_m", "maxdiff_vs_matrix"], rows)

    write_table("tab_recursions.tex", latex_table(
        caption=("Order $m$ of the scalar recursion "
                 "$\\varphi_n(z)=\\sum_{j=1}^{m}c_j(z)\\varphi_{n-j}(z)$ "
                 "obtained from $\\det[\\boldsymbol{I}-w(\\boldsymbol{A}+"
                 "z\\boldsymbol{B})]$, together with the largest absolute "
                 "difference between the recursion and the matrix embedding "
                 "over $p_2\\in\\{0.20,0.35,0.60\\}$ and $n\\le %d$." % nmax),
        label="tab:recursions",
        colspec="l cc cc r",
        header=[["Pattern", "$k$", "$r$", "$s$", "$m$", "Max PMF difference"]],
        rows=[["$%s$" % MATH[r_[0]], "%d" % r_[1], "%d" % r_[2],
               "%d" % r_[3], "%d" % r_[4], "%.2e" % r_[5]] for r_ in rows],
        notes=("The recursion always exists and its order never exceeds the "
               "embedded dimension, so evaluating it costs $O(nm)$ per "
               "sequence length against $O(ns)$ for a sparse matrix pass. "
               "The explicit coefficients are listed in "
               "Appendix~\\ref{app:recursions}.")))
    return rows


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--nmax", type=int, default=80)
    a = ap.parse_args()
    main(nmax=a.nmax)
