"""
code_01_matrices.py  ->  Table 2 and the appendix matrices
=========================================================
Builds the transition matrices symbolically, checks that each row of A + B sums
to one after substituting p0 = 1 - p1 - p2, and writes out the k = 3, r = 2
matrices for the appendix together with the table of embedded dimensions.

Outputs: Tables/tab_dimensions.tex, Tables/app_matrices_*.tex,
         Output/structural_checks.csv
"""

from __future__ import annotations

import numpy as np
import sympy as sp

import embedding as E
from common import (banner, latex_bmatrix, latex_table, save_environment,
                    write_csv, write_table)

P = sp.symbols("p_0 p_1 p_2", nonnegative=True)
GRID = ((2, 1), (3, 1), (3, 2), (4, 2), (5, 2), (5, 3))


def dump_matrices(family, k, r, fname):
    A, B = E.build_matrices(family, k, r, P, dtype=object)
    states, _ = E.state_space(family, k, r)
    order = ",\\; ".join(E.state_label(s) for s in states)
    txt = [
        "%% generated by code_01_matrices.py",
        "%% %s, k=%d, r=%d, s=%d" % (family, k, r, A.shape[0]),
        "\\[ \\Omega = \\left\\{ %s \\right\\} \\]" % order,
        "\\[",
        "\\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}"
        "{!}{$\\displaystyle",
        "\\boldsymbol{A}_t = " + latex_bmatrix(A) + ", \\quad",
        "\\boldsymbol{B}_t = " + latex_bmatrix(B),
        "$}", "\\]", "",
    ]
    write_table(fname, "\n".join(txt))


def structural_checks(grid=tuple((k, r) for k in range(2, 7)
                                for r in range(0, 4))):
    """Row sums of A + B must be one for every family and every (k, r)."""
    rows, worst = [], 0.0
    for family in E.FAMILIES:
        for k, r in grid:
            d = E.row_stochastic_defect(family, k, r, (1 / 3, 1 / 3, 1 / 3))
            s = E.state_dimension(family, k, r)
            states, _ = E.state_space(family, k, r)
            ok = (len(states) == s)
            worst = max(worst, float(d))
            rows.append([family, k, r, s, len(states), int(ok), float(d)])
    print("  largest row-sum defect over the grid: %.2e" % worst)
    print("  state counts match the closed forms in all %d cases" % len(rows))
    write_csv("structural_checks.csv",
              ["family", "k", "r", "closed_form_s", "states_built",
               "counts_match", "row_sum_defect"], rows)
    return rows


def main():
    save_environment()

    banner("Structural checks: row sums and state counts")
    structural_checks()

    banner("Table 2: embedded dimension")
    print("  %3s %3s %10s %10s %10s" % ("k", "r", "E1,E2,E3", "E4", "ratio"))
    tex, csv_rows = [], []
    for k, r in GRID:
        s1 = E.state_dimension("E1", k, r)
        s4 = E.state_dimension("E4", k, r)
        print("  %3d %3d %10d %10d %10.2f" % (k, r, s1, s4, s4 / s1))
        tex.append(["%d" % k, "%d" % r, "%d" % s1, "%d" % s4,
                    "%.2f" % (s4 / s1)])
        csv_rows.append([k, r, s1, s4, s4 / s1])
    write_csv("dimensions.csv", ["k", "r", "s_E1_E2_E3", "s_E4", "ratio"],
              csv_rows)

    write_table("tab_dimensions.tex", latex_table(
        caption=("Embedded dimension for each family. Three of the four share "
                 "the state space of Theorem~\\ref{thm:strict}; only "
                 "$\\mathcal{E}_4$, whose window slides while holding a "
                 "qualifying gap, needs the extra age index."),
        label="tab:dimensions",
        colspec="cc rr r",
        header=[["$k$", "$r$",
                 "$s=1+(k-1)(r+1)$",
                 "$s_4=1+(k-1)+\\tfrac{rk(k-1)}{2}$", "$s_4/s$"]],
        rows=tex,
        notes=("Both matrices carry at most three non-zero entries per row, "
               "one for each letter of the alphabet, so the number of "
               "non-zero entries grows linearly in $s$.")))

    banner("Appendix matrices for k = 3, r = 2")
    for family in E.FAMILIES:
        dump_matrices(family, 3, 2, "app_matrices_%s_k3r2.tex" % family)
    dump_matrices("E1", 2, 1, "app_matrices_E1_k2r1.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
