"""
common.py
=========
Paths, LaTeX writers and the environment stamp shared by the `code_*.py`
scripts in this folder.

Two layouts are supported. Beside the manuscript, the scripts sit in their own
folder and write to its siblings:

    ConditionalPGF_Paper/
        main.tex
        Python Codes/   this folder
        Tables/         generated LaTeX fragments, read by the manuscript
        Figures/        generated PNG figures
        Output/         CSV data and logs

In the code repository the scripts sit at the top level, and the same three
directories are created beside them. `ROOT` below resolves whichever applies, so
neither layout needs the scripts edited.
"""

from __future__ import annotations

import json
import os
import platform
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))

# Beside the manuscript the generated directories are siblings of this folder;
# in the flat repository layout they are siblings of the scripts themselves.
# The manuscript is what distinguishes the two.
_PARENT = os.path.dirname(HERE)
ROOT = _PARENT if os.path.isfile(os.path.join(_PARENT, "main.tex")) else HERE

TABLES = os.path.join(ROOT, "Tables")
FIGURES = os.path.join(ROOT, "Figures")
OUTPUT = os.path.join(ROOT, "Output")
for _d in (TABLES, FIGURES, OUTPUT):
    os.makedirs(_d, exist_ok=True)


def banner(title):
    print("\n" + "=" * 78 + "\n" + title + "\n" + "=" * 78)


def _write(path, text):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("  wrote %s" % os.path.relpath(path, ROOT).replace("\\", "/"))
    return path


def write_table(name, text):
    return _write(os.path.join(TABLES, name), text)


def write_output(name, text):
    return _write(os.path.join(OUTPUT, name), text)


def figure_path(name):
    return os.path.join(FIGURES, name)


def write_csv(name, header, rows):
    lines = [",".join(str(h) for h in header)]
    for row in rows:
        lines.append(",".join("" if v is None else str(v) for v in row))
    return write_output(name, "\n".join(lines) + "\n")


def latex_table(caption, label, colspec, header, rows,
                notes=None, small=True, star=False, arraystretch=None,
                resize=False):
    """Assemble a booktabs table ready for \\input{}.

    `rows` entries: a list of cells, or None to emit \\midrule.
    `header` may be one list of cells or a list of such lists.
    """
    env = "table*" if star else "table"
    L = ["%% generated by the scripts in 'Python Codes'; do not edit by hand",
         "\\begin{%s}[htbp]" % env, "\\centering",
         "\\caption{%s}" % caption, "\\label{%s}" % label]
    if arraystretch:
        L.append("\\renewcommand{\\arraystretch}{%s}" % arraystretch)
    if small:
        L.append("\\small")
    if resize:
        L.append("\\resizebox{\\textwidth}{!}{%")
    L += ["\\begin{tabular}{%s}" % colspec, "\\toprule"]
    hdr = header if header and isinstance(header[0], (list, tuple)) else [header]
    for line in hdr:
        L.append(" & ".join(str(c) for c in line) + " \\\\")
    L.append("\\midrule")
    for row in rows:
        L.append("\\midrule" if row is None
                 else " & ".join(str(c) for c in row) + " \\\\")
    L.append("\\bottomrule")
    L += ["\\end{tabular}"]
    if resize:
        L.append("}")
    if notes:
        # 0.98 rather than 1.0: a full-width minipage inside a float overruns
        # by a hair and LaTeX reports it as an overfull box
        L += ["\\\\[2pt]",
              "\\begin{minipage}{0.98\\linewidth}\\footnotesize %s\\end{minipage}"
              % notes]
    L += ["\\end{%s}" % env, ""]
    return "\n".join(L)


def latex_bmatrix(A):
    """LaTeX bmatrix for an array of numbers or sympy expressions."""
    import sympy as sp
    rows = []
    for i in range(A.shape[0]):
        rows.append(" & ".join(sp.latex(sp.sympify(A[i, j]))
                               for j in range(A.shape[1])))
    return "\\begin{bmatrix}\n" + " \\\\\n".join(rows) + "\n\\end{bmatrix}"


def sci_latex(x, digits=2):
    """1.62e-15 -> $1.62\\times10^{-15}$"""
    import math
    if x == 0:
        return "$0$"
    e = int(math.floor(math.log10(abs(x))))
    m = x / 10 ** e
    return "$%.*f\\times10^{%d}$" % (digits, m, e)


def environment_stamp():
    import numpy
    info = {
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "python": sys.version.split()[0],
        "implementation": platform.python_implementation(),
        "numpy": numpy.__version__,
        "platform": platform.platform(),
        "processor": platform.processor() or "unknown",
        "machine": platform.machine(),
        "logical_cpus": os.cpu_count(),
    }
    for mod in ("scipy", "sympy", "matplotlib"):
        try:
            info[mod] = __import__(mod).__version__
        except Exception:
            info[mod] = "not installed"
    return info


def save_environment():
    info = environment_stamp()
    write_output("environment.json", json.dumps(info, indent=2) + "\n")
    return info
